##
# Spring Profile Configuration
##
spring:
  profiles:
    active: prod
  ##
  # Hibernate Configuration
  ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

##
# Application Logging Configuration
##
logging:
  level:
    com:
      timeoverseer: debug

##
# Tomcat Configuration
##
server:
  port: 9090